on: 
    push: 
      tags: 
      - "v[0-9]+.[0-9]+.[0-9]+-alpha[0-9][0-9][0-9]"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Test
      working-directory: ./src/Serilog.Enrichers.Correlation.Tests
      run: dotnet test --configuration Release /p:Version="${VERSION}" /p:InformationalVersion="${VERSION}"
    - name: Package
      working-directory: ./src/Serilog.Enrichers.Correlation
      run: dotnet pack --configuration release --output ../../.nuget/ /p:Version="${VERSION}"
    - name: Push GITHUB
      working-directory: ./.nuget/
      run: dotnet nuget push "QPirate.Serilog.Enrichers.Correlation.${VERSION}.*nupkg" --source https://nuget.pkg.github.com/Qpirate/index.json --api-key ${GITHUB_TOKEN}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}